---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age166ya3wf9jucl4t3zk7xtkm0jtz29xm2y3025eppahw638x0dqe7sx98sj2"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age166ya3wf9jucl4t3zk7xtkm0jtz29xm2y3025eppahw638x0dqe7sx98sj2"
