# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.15.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret minecraft
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: java17
    resources:
      requests:
        cpu: 1000m
      limits:
        memory: 16Gi
    securityContext:
      runAsUser: &uid 568
      fsGroup: *uid
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    extraEnv:
      TZ: "${TIMEZONE}"
      ENABLE_AUTOPAUSE: FALSE
      MODS: https://cdn.modrinth.com/data/P7dR8mSH/versions/8GVp7wDk/fabric-api-0.91.6%2B1.20.2.jar,https://cdn.modrinth.com/data/F7wXag4i/versions/pjIlCcVy/inventorymanagement-1.4.0%2B1.20.2.jar,https://cdn.modrinth.com/data/TQTTVgYE/versions/xksYKkvF/fabric-carpet-1.20.2-1.4.121%2Bv231011.jar,https://cdn.modrinth.com/data/zQhsx8KF/versions/y3YGV2rC/servux-fabric-1.20.2-0.1.0.jar
      DATAPACKS: https://theswampmine.blob.core.windows.net/mods/double_shulker_shells_v1.3.6.zip,https://theswampmine.blob.core.windows.net/mods/fast_leaf_decay_v2.0.9.zip,https://theswampmine.blob.core.windows.net/mods/more_mob_heads_v2.12.1.zip,https://theswampmine.blob.core.windows.net/mods/unlock_all_recipes_v2.0.7.zip,https://theswampmine.blob.core.windows.net/mods/multiplayer_sleep_v2.6.4.zip,https://theswampmine.blob.core.windows.net/mods/track_raw_statistics_v1.7.0.zip,https://theswampmine.blob.core.windows.net/mods/track_statistics_v1.1.5.zip,https://theswampmine.blob.core.windows.net/mods/villager_death_messages_v1.2.5.zip,https://theswampmine.blob.core.windows.net/mods/craftable_Bundles_MC1.20-1.20.4.zip
    CF_API_KEY: $$2a$$10$$BebpL47dj9vfAfkUavroFe87YkrWHwR68vt7BHO4VbnRSWMEtRSNS
    CURSEFORGE_FILES: 4793145
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-server
    serviceAnnotations:
      #io.cilium/lb-ipam-ips: "${SVC_MINECRAFT_ADDR}"
      mc-router.itzg.me/externalServerName: "minecraft.${SECRET_DOMAIN}"
    minecraftServer:
      eula: "TRUE"
      version: 1.20.2
      type: FABRIC
      forceReDownload: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 8192M
      difficulty: hard
      spawnProtection: 0
      maxTickTime: -1
      gameMode: survival
      pvp: false
      onlineMode: "TRUE"
      ops: "Valdrith9422"
      motd: "248Craft"
      worldSaveName: 248Craft
      viewDistance: 16
      spigetResources:
      - 36618 #Prom Exporter
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceType: LoadBalancer
      extraPorts:
      - name: metrics
        containerPort: 9225
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 9225
        ingress:
          enabled: false
      - name: map
        containerPort: 8123
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 8123
        ingress:
          ingressClassName: external
          enabled: true
          hosts:
          - name: &host "minecraft.${SECRET_DOMAIN}"
            path: /
          tls:
          - secretName: *host
            hosts:
            - *host
  valuesFrom:
  - kind: Secret
    name: *secret
    valuesKey: RCON_PASSWORD
    targetPath: minecraftServer.rcon.password
