# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.20.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret minecraft
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: latest
    resources:
      requests:
        cpu: 1000m
      limits:
        memory: 16Gi
    securityContext:
      runAsUser: &uid 568
      fsGroup: *uid
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    extraEnv:
      TZ: "${TIMEZONE}"
      ENABLE_AUTOPAUSE: FALSE
      MODS: https://www.curseforge.com/minecraft/mc-mods/fabric-api/download/5618309
      DATAPACKS: https://theswampmine.blob.core.windows.net/mods/anti%20enderman%20grief%20v1.1.8%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/double%20shulker%20shells%20v1.3.8%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/durability%20ping%20v1.1.8%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/fast%20leaf%20decay%20v2.0.11%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/more%20mob%20heads%20v2.14.0%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/multiplayer%20sleep%20v2.6.8%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/player%20head%20drops%20v1.1.8%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/track%20raw%20statistics%20v1.7.4%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/track%20statistics%20v1.1.10%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/unlock%20all%20recipes%20v2.0.9%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/villager%20death%20messages%20v1.2.10%20(MC%201.21-1.21.1).zip,https://theswampmine.blob.core.windows.net/mods/wandering%20trades%20hermit%20edition%20v1.9.3%20(MC%201.21-1.21.1).zip
      OVERRIDE_SERVER_PROPERTIES: true
    CF_API_KEY: $$2a$$10$$BebpL47dj9vfAfkUavroFe87YkrWHwR68vt7BHO4VbnRSWMEtRSNS
    #CURSEFORGE_FILES: 4793145
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-server
    serviceAnnotations:
      #io.cilium/lb-ipam-ips: "${SVC_MINECRAFT_ADDR}"
      mc-router.itzg.me/externalServerName: "minecraft.${SECRET_DOMAIN}"
    minecraftServer:
      eula: "TRUE"
      version: latest
      type: FABRIC
      forceReDownload: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 16384M
      difficulty: hard
      spawnProtection: 0
      maxTickTime: -1
      gameMode: survival
      pvp: false
      onlineMode: true
      ops: "Valdrith9422"
      motd: "248Craft"
      worldSaveName: 248Craft
      viewDistance: 16
      spigetResources:
      - 36618 #Prom Exporter
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceType: LoadBalancer
      extraPorts:
      - name: metrics
        containerPort: 9225
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 9225
        ingress:
          enabled: false
      - name: map
        containerPort: 8123
        protocol: TCP
        service:
          enabled: true
          embedded: false
          type: ClusterIP
          port: 8123
        ingress:
          ingressClassName: external
          enabled: true
          hosts:
          - name: &host "minecraft.${SECRET_DOMAIN}"
            path: /
          tls:
          - secretName: *host
            hosts:
            - *host
  valuesFrom:
  - kind: Secret
    name: *secret
    valuesKey: RCON_PASSWORD
    targetPath: minecraftServer.rcon.password

