ansible_become_pass: ENC[AES256_GCM,data:163O,iv:cT27giKJ8mIq57cU2Eu4408ACAq1g6uunrmd5hvOHEQ=,tag:yDu41ztdrm9pXs2qlrEC6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166ya3wf9jucl4t3zk7xtkm0jtz29xm2y3025eppahw638x0dqe7sx98sj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZUI2aDBobko5dnRPRnBT
            NjJXV3B1U3hsTThEYlNkK3pNYXA4NHR0eWdrCkdiZm8zM1pvLzZrZmpKeVBINTZv
            NDdPODY2ZCtDV2xMcGw1Qm9CWHlWUmsKLS0tIFNzUlF1eWplZkhSaHljNCtGTCti
            M0duUitjMUxselZLM3VmcUNUSDYzZHMK4j6PhFWGrHley249XdorygfN4pRsKt/G
            5hx2e1YYhIrbrIa5YUDxkUVhWmcalS97U3tg8fJnoVu6Emr//AMVNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T21:40:38Z"
    mac: ENC[AES256_GCM,data:GfCXPqVBr+6TrL9jUhaZNYFVOV5m/U/D3mQ44bODhRcu93CgX66MRSt3rWW7mY+dEfGKBOoXwUiOgohOKEapcvfBXkiYCurV2XuWiy68qQigmJh7JtW+XpX/bwtIMMDGPFdFX52sE6o2o4Xnf7fGTYxgSlAsevy+siLnHjoqSD8=,iv:Q91NjVSBOKe3Z9UPHRvndgeRu9q/5RmxX0ZWzTZIGlQ=,tag:ZlS9DLxOw9cd/dVI1S3UKQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
