ansible_become_pass: ENC[AES256_GCM,data:AiAu0dD18ku74uD/vorYvu/EPzd0ZeI3fwEz9G2Su0YYeMyXAr4Z5jwH95bcPIsa5i/zNGW/KQVx,iv:2XQweJxTQmqGVUvZKy0GoYFYgJi1z0ERMb55va25hAI=,tag:e9t/1PiumKRADXZj+VdKmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12lhrg8fft3de6c5ulkk89s9j2l7pnq99uwvtpmvaqrle76re3ets8vq4vl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVE9qM1AxZ01iY0pEWlJC
            bWVZejN5cU1SUHNGOW1tV2tXWGRTcyt5OWdVCmFTZ3Qyc3NHS2lRVDRiM25jUGRi
            cTQ1aUV6NWVtNWJlTVdNYlY2OC9LZXcKLS0tIEtTbTFqd3l3UjFlb08xWTNMRnJr
            eHRGamxCU2p4SFZqMHN1L2VPOXdnN28KwFXfZM8pnaX2T995+/VZusn7/x7Tvejq
            jF084Olw9EW95D0ozCGvyydTj7xC1xCqYGkzmcuQx/38//nyyyDesg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T21:15:03Z"
    mac: ENC[AES256_GCM,data:fqPZXDqUNBJ67tz/myVuiQM8l/LkBice80FaG9tEv6aH+ay02AyTHQJDomD/P1KOO2xjp6ONmIVzL7iYgEn0O85RLlGvv5yIfqK3nBo7cUnT0EP/l7Zbp1MKJVgBf8yiUz6PJY1DXx5jXa2finLSloV2EOd36OZMlsy/cDHg1x8=,iv:l0vcsttasS3H5A/+mVr8j4YgoIZZlUfbewYnhmAK+Vg=,tag:qWjyPGhGOpghnaGRjHdSQQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
