ansible_become_pass: ENC[AES256_GCM,data:1T5F,iv:CmGpZa1fMsN6yG6hCZbAx2J6MH9yDYwFHd1FN9ZTRpk=,tag:g1/3bs0XuwTc8v/tohiIZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166ya3wf9jucl4t3zk7xtkm0jtz29xm2y3025eppahw638x0dqe7sx98sj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MUZwNFd1ZytFODFzUVZB
            aTlKSCtBWW5HaUNiMVNlcnhURThoTVZoTUZ3CkpQdEdPL1FuWEVnelF2c2VnblB5
            T1gwTEhwS0xSY1VOd0x5d2hGSENjRmsKLS0tIC9rbkVFNGNVQzBNUmhkdEVZRU1h
            RjFObDBVdUVibjNmdmE0RExHWk1TWHcKvsn5BPmhqdrZZm1Kd1RaYvU0bkTuNCA2
            NUdqOk22PBQ1udLWjEZdngXPjuuvN6PC42xmYfjjw3IttaxOOkUv3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T21:40:38Z"
    mac: ENC[AES256_GCM,data:yDapaxN+p6yIb5U45eDmiEDgmk/B0iwkqMsXwxOuuNoNDo0DEkXFJUeooGuv5/0/1Z5FGeztw1q936bij22rBoR9URgKUfLUHO7tACb9dXy16NpUxbtGX+Kx0cPK4OYSZAbOCCgpzJ49MmGbau38ohY+PrtGyMoEuwFO9i7/5As=,iv:dXZL27Y6hpP5f6yP8g9GPqBQDF6DpPLe3TUl7lQ820c=,tag:FAQ5qwyWXd3ISurBgLf6Jg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
