apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:IRd6rYNANw55rKTp/snI62+NvYflvW8=,iv:myHtJNLH+deFz9EFy0wGSmazNy72A/KoUpwxbCgN2LI=,tag:5ea+ALsiiH00gJYDK1m4ag==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VR07jsE5flAdS+wm5TZ9ybQ7+8Q3/uskEthWxHWw4jgNG7sX,iv:b/+PYgLUcu7O3vR3gBGqRb/QVmjJij3Zm8eEuHN4jHw=,tag:up4e8nKUjrvRWsgfoz++uw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:2aJGEifEhHmnrrJ9,iv:uSWLL6u/Dszaa1rKSWBHyfPRZXYEwlesiO2d+zIfOec=,tag:c9U9VK8JsX41FAinphIffQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age166ya3wf9jucl4t3zk7xtkm0jtz29xm2y3025eppahw638x0dqe7sx98sj2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUlZzU0lNNjM2KzNXNHpG
            MkhqY2JCWU1saGxwcFNXR01sUXBsQ0thVFc4CktUVVdXRGR3YXBCUzY4cjJsZFFz
            NkFIZjFCRGNkNld0UTlWZVN1dnY1d2sKLS0tIEhnajArc2VwMER0cDRLL3ppNHAy
            TXlEMklaR01JdmFnWk5RMlMyeWlHVTAKr2j2l3gmYuXdWPK+NSlLK8i9s+SVebjP
            v1drFnaDcNlle32CuTwVCW+QeBDzEejLjnevbSxMw54EPRDcwrOblw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-15T21:41:01Z"
    mac: ENC[AES256_GCM,data:HOxDtmO+eJ9Ys1yiVO0CyKCMU0w6w9QA/yX1TZmlIEsk7LYKcNYBs0dmUSlb186aD4t6K25bmOnsIIzVai/waiOg5PBLH1KdujRlztyq/j3y7FhjvQR9YI7NrTtBz5zXNxA3KT4IxcdIXGG2PfKr+dYXHO92+pZUPyFXq0mBcSE=,iv:+BjkZDAPvV/afNEmjgVI6oGgt3Ncg8ZTCrO/zds4d24=,tag:tPH2cBn2Ak1VsiMPW2T19A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
