---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.32.5.7349-8f4248874@sha256:805ad80226d54f03c21efe84979558e7c3d0b07f345b9c929ff11de8cc216151

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.1.215"
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        ingressClassName: "internal"
        hosts:
          - host: &host plex.theswamp.home
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

#    persistence:
#      nfs-nas-media:
#        enabled: true
#        mountPath: /storage/media
#        path: /Videos
#        server: 192.168.1.5
#        type: nfs
#      transcode:
#        enabled: true
#        type: emptyDir

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 65539

    resources:
      requests:
        cpu: 5m
        memory: 13710M
      limits:
        memory: 13710M

#    volumeClaimTemplates:
#      - name: config
#        mountPath: /config
#        accessMode: ReadWriteOnce
#        size: 200Gi
#        storageClass: ceph-block


