---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          SecurityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 65539
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.41.2.9200-c6bbc1b53@sha256:1f28b5e5a964481f80e76db3c986082d2fc3bca2d16d2742704e9adf8349c79c
            env:
              - name: PLEX_CLAIM
                value: claim-3HcLYsR95MfcypXu1TQ3
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 5m
                memory: 13710M
              limits:
                memory: 13710M

    service:
      app:
        controller: plex
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.1.215"
        ports:
          http:
            port: 32400

    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        ingressClassName: "internal"
        hosts:
          - host: &host plex.theswamp.home
            paths:
              - path: /
                service:
                  identifier: app
                  port: http


    persistence:
      nfs-nas-media:
        enabled: true
        mountPath: /Media
        path: /
        server: 192.168.1.6
        type: nfs
      transcode:
        enabled: true
        type: emptyDir

      volumeClaimTemplates:
        - name: config
          mountPath: /config
          accessMode: ReadWriteOnce
          size: 200Gi
          storageClass: ceph-block



